kind: Deployment
apiVersion: apps/v1
metadata:
  name: multicluster-resiliency-addon-agent
  namespace: {{ .AgentNamespace }}
spec:
  replicas: {{ .AgentReplicas }}
  selector:
    matchLabels:
      addon: multicluster-resiliency-addon-agent
  template:
    metadata:
      labels:
        addon: multicluster-resiliency-addon-agent
    spec:
      serviceAccountName: multicluster-resiliency-addon-agent-sa
      containers:
        - name: multicluster-resiliency-addon-agent
          image: {{ .AgentImage }}
          imagePullPolicy: IfNotPresent
          args:
            - agent
            - --spoke-name={{ .SpokeName }}
            - --hub-kubeconfig=/etc/hub/kubeconfig
            - --agent-namespace={{ .AgentNamespace }}
          volumeMounts:
            - name: hub-kubeconfig
              mountPath: /etc/hub/
              readOnly: true
      volumes:
        - name: hub-kubeconfig
          secret:
            secretName: {{ .KubeConfigSecret }}
