# This kustomize file is used for kustomizing load CRDs.
# Do not use directly, use as part of the overall Addon deployment (start at default).
resources:
  - appeng.ecosystem.redhat.com_resilientclusters.yaml

patches:
  - path: patches/crd_certmanager_annotations.yaml #[CERT_MANAGER]

labels:
  - pairs:
      app.kubernetes.io/component: addon-core
